.\" Manpage for pcbasic
.TH man 1 "17 August 2014" "1.1" "pcbasic man page"
.SH NAME
PC-BASIC 3.23: a BASIC intepreter compatible with GW-BASIC 3.23
.SH SYNOPSIS
pcbasic --options
.SH DESCRIPTION
PC-BASIC 3.23 is a BASIC interpreter compatible with Microsoft GW-BASIC, Tandy 1000 BASIC
and IBM PCjr Cartridge BASIC. 
.SH EXAMPLES
pcbasic                             
    Runs a graphical interactive session.
.PP
pcbasic PROGRAM.BAS                 
    Runs PROGAM.BAS in a graphical session.
.PP
pcbasic --mount C:/home/me
    Runs a graphical session with the "C:" drive ampped to /home/me  
.PP
pcbasic --preset=tandy              
    Runs an interactive session in Tandy 1000 mode.                    
.PP
pcbasic PCJRPROG.BAS --preset=pcjr -q 
    Runs PCJRPROG.BAS in PCjr mode and quit PC-BASIC when the program ends.                    
.PP
pcbasic -b                          
    Runs a command-line interactive session.
.PP
pcbasic -bqe "print 1+1"            
    Executes the command directly on the command line - returns 2 and exits.
.PP
pcbasic PROGRAM.BAS --conv a        
    Writes listing of PROGRAM.BAS to standard output in MS-DOS ASCII format.
.PP
pcbasic -l PROGRAM.BAS -bqe "LIST"  
    Writes listing of PROGRAM.BAS to standard output as UTF-8 text.
.PP
.SH OPTIONS
  basic_program         Input program file to run (default), load or convert.

.SH FILES
.I ./info/PCBASIC.INI
Configuration file. The configuration options correspond to the command-line option: if a command-line option is given as --option VALUE,
the corresponding entry in PCBASIC.INI is option=VALUE. Presets (such as cga and tandy) are defined in this file as groups of options under a header in square brackets. 
.SH BUGS
This is beta software; many bugs are still expected to pop up. Please inform the author through the sourceforge project page at http://sourceforge.net/projects/pcbasic/
.SH AUTHOR
Rob Hagemans
